// pattern: Functional Core
// CourtListener court_id -> Bluebook citation abbreviation, used to render the
// court in a case account profile bio. Generated from CourtListener's
// /api/rest/v4/courts/ (authoritative `citation_string`) on 2026-06-10; federal
// courts only (jurisdictions F, FD, FB, FS). Re-pull that endpoint to regenerate.
// Unknown ids fall back to the raw court_id via courtLabel.

const COURT_LABELS: Record<string, string> = {
  ag: "Op. Att\u2019y Gen.",
  akb: "Bankr. D. Alaska",
  akd: "D. Alaska",
  ald: "D. Ala.",
  almb: "Bankr. M.D. Ala.",
  almd: "M.D. Ala.",
  alnb: "Bankr. N.D. Ala.",
  alnd: "N.D. Ala.",
  alsb: "Bankr. S.D. Ala.",
  alsd: "S.D. Ala.",
  arb: "Bankr. D. Ariz.",
  areb: "Bankr. E.D. Ark.",
  ared: "E.D. Ark.",
  arwb: "Bankr. W.D. Ark.",
  arwd: "W.D. Ark.",
  asbca: "A.S.B.C.A.",
  azd: "D. Ariz.",
  bia: "BIA",
  bpai: "B.P.A.I.",
  bta: "B.T.A.",
  bva: "Board of Vet. App.",
  ca1: "1st Cir.",
  ca10: "10th Cir.",
  ca11: "11th Cir.",
  ca2: "2d Cir.",
  ca3: "3rd Cir.",
  ca4: "4th Cir.",
  ca5: "5th Cir.",
  ca6: "6th Cir.",
  ca7: "7th Cir.",
  ca8: "8th Cir.",
  ca9: "9th Cir.",
  caca: "C. Cal.",
  cacb: "Bankr. C.D. Cal.",
  cacd: "C.D. Cal.",
  cadc: "D.C. Cir.",
  caeb: "Bankr. E.D. Cal.",
  caed: "E.D. Cal.",
  cafc: "Fed. Cir.",
  californiad: "D. Cal.",
  canalzoned: "D.C.Z.",
  canb: "Bankr. N.D. Cal.",
  cand: "N.D. Cal.",
  casb: "Bankr. S.D. Cal.",
  casd: "S.D. Cal.",
  cavc: "Vet. App.",
  cc: "Ct. Cl.",
  ccpa: "C.C.P.A.",
  circtdel: "Cir. Ct. Del.",
  circtnc: "Cir. Ct. N.C.",
  circtndfl: "C.C.N.D. Fla.",
  circtsdfl: "C.C.S.D. Fla.",
  circttenn: "Cir. Ct. Tenn.",
  cit: "Ct. Intl. Trade",
  cob: "Bankr.D. Colo.",
  cod: "D. Colo.",
  com: "Comm. Ct.",
  ctappindterr: "Ct. App. Ind. Terr.",
  ctb: "Bankr. D. Conn.",
  ctd: "D. Conn.",
  cusc: "Cust. Ct.",
  dcb: "Bankr. D.C.",
  dcd: "D.D.C.",
  deb: "Bankr. D. Del.",
  ded: "D. Del.",
  eca: "Emer. Ct. App.",
  fisc: "FISA Ct.",
  fiscr: "FISA Ct. Rev.",
  fld: "D. Fla.",
  flmb: "Bankr. M.D. Fla.",
  flmd: "M.D. Fla.",
  flnb: "Bankr. N.D. Fla.",
  flnd: "N.D. Fla.",
  flsb: "Bankr. S.D. Florida",
  flsd: "S.D. Fla.",
  gad: "D. Ga.",
  gamb: "Bankr. M.D. Ga.",
  gamd: "M.D. Ga.",
  ganb: "Bankr. N.D. Ga.",
  gand: "N.D. Ga.",
  gasb: "Bankr. S.D. Ga.",
  gasd: "S.D. Ga.",
  gub: "Bankr. D. Guam",
  gud: "D. Guam",
  hib: "Bankr. D. Haw.",
  hid: "D. Haw.",
  iad: "D. Iowa",
  ianb: "Bankr. D. Iowa",
  iand: "N.D. Iowa",
  iasb: "Bankr. S.D. Iowa",
  iasd: "S.D. Iowa",
  idb: "Bankr. D. Idaho",
  idd: "D. Idaho",
  ilcb: "Bankr. C.D. Ill.",
  ilcd: "C.D. Ill.",
  illinoisd: "D. Ill.",
  illinoised: "E.D. Ill.",
  ilnb: "Bankr. N.D. Ill.",
  ilnd: "N.D. Ill.",
  ilsb: "Bankr. S.D. Ill.",
  ilsd: "S.D. Ill.",
  indianad: "D. Ind.",
  innb: "Bankr. N.D. Ind.",
  innd: "N.D. Ind.",
  insb: "Bankr. S.D. Ind.",
  insd: "S.D. Ind.",
  jpml: "J.P.M.L.",
  ksb: "Bankr. D. Kan.",
  ksd: "D. Kan.",
  kyd: "D. Ky.",
  kyeb: "Bankr. E.D. Ky.",
  kyed: "E.D. Ky.",
  kywb: "Bankr. W.D. Ky.",
  kywd: "W.D. Ky.",
  lad: "D. La.",
  laeb: "Bankr. E.D. La.",
  laed: "E.D. La.",
  lamb: "Bankr. M.D. La.",
  lamd: "M.D. La.",
  lawb: "Bankr. W.D. La.",
  lawd: "W.D. La.",
  mab: "Bankr. D. Mass.",
  mad: "D. Mass.",
  mdb: "Bankr. D. Md.",
  mdd: "D. Maryland",
  meb: "Bankr. D. Me.",
  med: "D. Me.",
  michd: "D. Mich.",
  mieb: "Bankr. E.D. Mich.",
  mied: "E.D. Mich.",
  missd: "D. Miss.",
  miwb: "Bankr. W.D. Mich.",
  miwd: "W.D. Mich.",
  mnb: "Bankr. D. Minn.",
  mnd: "D. Minnesota",
  mod: "D. Mo.",
  moeb: "Bankr. E.D. Mo.",
  moed: "E.D. Mo.",
  mowb: "Bankr. W.D. Mo.",
  mowd: "W.D. Mo.",
  msnb: "Bankr. N.D. Miss.",
  msnd: "N.D. Miss.",
  mspb: "MSPB",
  mssb: "Bankr. S.D. Miss.",
  mssd: "S.D. Miss.",
  mtb: "Bankr. D. Mont.",
  mtd: "D. Mont.",
  ncd: "D.N.C.",
  nceb: "Bankr. E.D.N.C.",
  nced: "E.D.N.C.",
  ncmb: "Bankr. M.D.N.C.",
  ncmd: "M.D.N.C.",
  ncwb: "Bankr. W.D.N.C.",
  ncwd: "W.D.N.C.",
  ndb: "Bankr. D.N.D.",
  ndd: "D.N.D.",
  nebraskab: "Bankr. D. Neb.",
  ned: "D. Neb.",
  nhb: "Bankr. D.N.H.",
  nhd: "D.N.H.",
  njb: "Bankr. D.N.J.",
  njd: "D.N.J.",
  nmb: "Bankr. D.N.M.",
  nmd: "D.N.M.",
  nmib: "Bankr. N. Mar. I.",
  nmid: "N. Mar. I.",
  nvb: "Bankr. D. Nev.",
  nvd: "D. Nev.",
  nyd: "D. N.Y.",
  nyeb: "Bankr. E.D.N.Y.",
  nyed: "E.D.N.Y",
  nynb: "Bankr. N.D.N.Y.",
  nynd: "N.D.N.Y.",
  nysb: "Bankr. S.D.N.Y.",
  nysd: "S.D.N.Y.",
  nywb: "Bankr. W.D.N.Y.",
  nywd: "W.D.N.Y.",
  ohiod: "D. Ohio",
  ohnb: "Bankr. N.D. Ohio",
  ohnd: "N.D. Ohio",
  ohsb: "Bankr. S.D. Ohio",
  ohsd: "S.D. Ohio",
  okeb: "Bankr. E.D. Okla.",
  oked: "E.D. Okla.",
  oknb: "Bankr. N.D. Okla",
  oknd: "N.D. Okla.",
  okwb: "Bankr. W.D. Okla.",
  okwd: "W.D. Okla.",
  olc: "OLC",
  orb: "Bankr. D. Or.",
  ord: "D. Or.",
  orld: "D. Orleans",
  paeb: "Bankr. E.D. Pa.",
  paed: "E.D. Pa.",
  pamb: "Bankr. M.D. Penn.",
  pamd: "M.D. Penn.",
  pawb: "Bankr. W.D. Pa.",
  pawd: "W.D. Pa.",
  pennsylvaniad: "D. Pa.",
  philadeptjust: "Phila. Dept. Just.",
  prb: "Bankr. D.P.R.",
  prd: "D.P.R.",
  ptab: "P.T.A.B.",
  reglrailreorgct: "Regl. Rail Reorg. Act",
  rib: "Bankr. D.R.I.",
  rid: "D.R.I.",
  scb: "Bankr. D.S.C.",
  scd: "D.S.C.",
  scotus: "SCOTUS",
  sdb: "Bankr. D.S.D.",
  sdd: "D.S.D.",
  southcarolinaed: "E.D.S.C.",
  southcarolinawd: "W.D.S.C.",
  superctsdfla: "Super. Ct. S.D. Fla.",
  tax: "Tax Ct.",
  tecoa: "Temp. Emerg. Ct. App.",
  tennessed: "D. Tenn.",
  tennesseeb: "Bankr. D. Tenn.",
  texd: "D. Tex.",
  tneb: "Bankr. E.D. Tenn.",
  tned: "E.D. Tenn.",
  tnmb: "Bankr. M.D. Tenn.",
  tnmd: "M.D. Tenn.",
  tnwb: "Bankr. W.D. Tenn.",
  tnwd: "W.D. Tenn.",
  ttab: "T.T.A.B.",
  txeb: "Bankr. E.D. Tex.",
  txed: "E.D. Tex.",
  txnb: "Bankr. N.D. Tex.",
  txnd: "N.D. Tex.",
  txsb: "Bankr. S.D. Tex.",
  txsd: "S.D. Tex.",
  txwb: "Bankr. W.D. Tex.",
  txwd: "W.D. Tex.",
  uscfc: "Fed. Cl.",
  uscirct: "U.S. Cir. Ct.",
  uslandoffice: "US Land Office",
  utb: "Bankr. D. Utah",
  utd: "D. Utah",
  vad: "D. Va.",
  vaeb: "Bankr. E.D. Va.",
  vaed: "E.D. Va.",
  vawb: "Bankr. W.D. Va.",
  vawd: "W.D. Va.",
  vib: "Bankr. D.V.I.",
  vid: "D.V.I.",
  vtb: "Bankr. D. Vt.",
  vtd: "D. Vt.",
  waeb: "Bankr. E.D. Wash.",
  waed: "E.D. Wash.",
  washd: "D. Wash.",
  wawb: "Bankr. W.D. Wash.",
  wawd: "W.D. Wash.",
  wieb: "Bankr. E.D. Wis.",
  wied: "E.D. Wis.",
  wisd: "D. Wis.",
  wiwb: "Bankr. W.D. Wis.",
  wiwd: "W.D. Wis.",
  wvad: "D. W.Va.",
  wvnb: "Bankr. N.D.W. Va.",
  wvnd: "N.D.W. Va.",
  wvsb: "Bankr. S.D.W. Va.",
  wvsd: "S.D.W. Va",
  wyb: "Bankr. D. Wyo.",
  wyd: "D. Wyo.",
};

// Falls back to the raw id for any court not in the map (an opaque slug beats
// a wrong label or a crash).
export function courtLabel(id: string): string {
  return COURT_LABELS[id] ?? id;
}
